#!/bin/bash -eu

port="$(modelctl get http.port)"
host="$(modelctl get http.host)"

extra_args=()

verbose="$(modelctl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--verbose)
fi

# The engine must set --mmproj if a multimodal projector is needed

set -x
exec llama-server \
  --model "$MODEL_FILE" \
  --port "$port" \
  --host "$host" \
  "${extra_args[@]}" \
  "$@"
