#!/bin/bash -eu

port="$(modelctl get http.port)"
host="$(modelctl get http.host)"

extra_args=()

verbose="$(modelctl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--log_level DEBUG)
fi

# The --source_model and --model_repository_path args are pull-related arguments.
# OVMS does not work when using the alternative --model_name and --model_path arguments.
# Issue: https://github.com/openvinotoolkit/model_server/issues/3492

# Set --pipeline_type VLM  to working around an issue with the default
# continuous batching pipeline, VLM_CB

# The engine must additionally set --target_device CPU|GPU|NPU|etc

set -x
ovms \
    --rest_port "$port" \
    --rest_bind_address "$host" \
    --source_model "$MODEL_NAME" \
    --model_repository_path "$MODEL_PATH" \
    --pipeline_type VLM \
    --task text_generation \
    --cache_size 2 \
    "${extra_args[@]}" \
    "$@"
