name: Build PR when labeled

on:
  pull_request:
    types: [ labeled ]

jobs:
  remove-label:
    uses: canonical/inference-snaps-dev/.github/workflows/remove-label.yaml@v2
    with:
      label: ${{ vars.PR_BUILD_TRIGGER_LABEL }}

  build-and-publish:
    if: github.event.label.name == vars.PR_BUILD_TRIGGER_LABEL
    uses: canonical/inference-snaps-dev/.github/workflows/build-publish-snap.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ self-hosted, amd64, noble, large ]
          - [ self-hosted, arm64, noble, large ]
    with:
      runner: "${{ toJSON(matrix.runner) }}"
      init-build-script: 'prepare-models.sh'
      # Publish to a channel with the pr number in it
      publish-channel: latest/edge/pr-${{ github.event.pull_request.number }} # Add track if needed, e.g., 24/latest/edge/pr-#
    secrets:
      store-credentials: ${{ secrets.STORE_LOGIN }}
